server:
  port: 0

spring:
  datasource:
    url: jdbc:mysql://Localhost:3306/selenium
    username: root
    password: Snehal@6382
    driver-class-name: com.mysql.cj.jdbc.Driver

addressservice:
  base:
    url: http://localhost:8082/